@echo off
call echo building project...
call browserify ./app/script.js -o ./app/bundle.js --debug
call echo browserify complete...
call terser ./app/bundle.js --compress -o ./app/bundle.min.js
call echo minify complete...
call browserify ./docs/guide_gen.js -o ./docs/guide_gen_bundle.js --debug
call echo docgen browserify complete...
call echo build complete!